import { Inter } from "next/font/google";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "다르크 협회",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=yes"></meta>
      <meta name="naver-site-verification" content="0fa832e430a4813bbb6a5ea447baacd5a39d561b" />
    </html>
  );
}
